dgs:
  graphql:
    graphiql:
      enabled: true
    path: /shows
spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    # if this prop is not set, spring tries to execute data.sql BEFORE db schema is automatically created by hibernate
    defer-datasource-initialization: true
